spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ubuntu:3306/mobile_dj?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: zlb/zlb/zlb
  redis:
    database: 0
    host: ubuntu
    port: 6379
    password: zlb/zlb/zlb
    jedis:
      pool:
        max-active: 8
        max-wait: 0
        max-idle: 10
        min-idle: 0
    timeout: 3000
  data:
    mongodb:
      host: ubuntu
      port: 27017 # mongodb的连接端口号
      database: mall-port # mongodb的连接的数据库

mybatis:
  config-location: classpath:mybatis-config.xml

local:
  host: http://192.168.2.120:8080/
  # 验证码图片放置的本机文件夹
  verifyPath: D:\verify\
  image: D:\img\
  # 轮播图片存放的本机文件夹
  slidePath: D:\slide\

# 教务
jw:
  host: 202.199.128.21

# 后勤爬虫的各种配置
logistics:
  host: https://nanqu.56team.com

# 小程序配置
mini:
  appId: wxe1f564d00f76340a
  secret: ec547e58ed84fcbbee3a7e24a5823cc8
