spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dj.xiaoshi98.top:3306/mobile_dj?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: zlb/zlb/zlb
  redis:
    database: 0
    host: dj.xiaoshi98.top
    port: 6379
    password: zlb/zlb/zlb
    jedis:
      pool:
        max-active: 8
        max-wait: 0
        max-idle: 10
        min-idle: 0
    timeout: 3000

mybatis:
  config-location: classpath:mybatis-config.xml
# 证书配置
server:
  port: 443
  ssl:
    key-store: "classpath:dj.xiaoshi98.top.jks"
    key-store-password: p0dV6nyi
    key-store-type: JKS
    key-alias: alias

local:
  host: https://dj.xiaoshi98.top:443/
  # 验证码图片放置的本机文件夹
  #  verifyPath: D:\verify\
  verifyPath: /usr/local/dj/verify/
  #  image: D:\img\
  image: /usr/local/dj/img/
  # 轮播图片存放的本机文件夹
  #  slidePath: D:\slide\
  slidePath: /usr/local/dj/slide/

# 教务
jw:
  host: 202.199.128.21

# 后勤爬虫的各种配置
logistics:
  host: https://nanqu.56team.com

# 小程序配置
mini:
  appId: wxe1f564d00f76340a
  secret: ec547e58ed84fcbbee3a7e24a5823cc8
